log_info("akhenaten: localization config started")

localization = [
  {key: "#popup_dialog_quit", group:5, id:0 },
  {key: "#popup_dialog_open_trade", group:5, id:2 },
  {key: "#popup_dialog_send_goods", group:5, id:7 },
  {key: "#popup_dialog_not_enough_goods", group:5, id:8 },
  {key: "#popup_dialog_no_legions_available", group:5, id:10 },
  {key: "#popup_dialog_no_legions_selected", group:5, id:12 },
  {key: "#popup_dialog_send_troops", group:5, id:14 },
  {key: "#popup_dialog_delete_fort", group:5, id:16 },
  {key: "#popup_dialog_delete_bridge", group:5, id:20 },
  {key: "#popup_dialog_quit_without_saving", group:5, id:22 },
  {key: "#exit_without_saving", group:5, id:23 },
  {key: "#popup_dialog_no_festival_square", group:5, id:88 },
  {key: "#popup_dialog_delete_dynasty", group:5, id:90 },
  {key: "#popup_dialog_no_dynasty", group:5, id:94 },
  {key: "#replay_mission", group:1, id:2 },
  {key: "#granary_info_title", group:98, id:0 },
  {key: "#granary_no_road_access", group:69, id:25 },
  {key: "#granary_kingdom_supplies_grain", group:98, id:4 },
  {key: "#granary_storing", group:98, id:2 },
  {key: "#granary_space_for", group:98, id:3 },
  {key: "#granary_units", group:8, id:17 },
  {key: "#chief_overseer", group:61, id:0 },
  {key: "#chief_adv_sentiment", group:61, id:1 },
  {key: "#chief_adv_migration", group:61, id:2 },
  {key: "#chief_adv_workers", group:61, id:3 },
  {key: "#chief_adv_foodstocks", group:61, id:4 },
  {key: "#chief_adv_foodconsumption", group:61, id:5 },
  {key: "#chief_adv_health", group:61, id:6 },
  {key: "#chief_adv_religion", group:61, id:7 },
  {key: "#chief_adv_finance", group:61, id:8 },
  {key: "#chief_adv_crime", group:61, id:9 },
  {key: "#chief_adv_military", group:61, id:10 },
  {key: "#chief_adv_kingdom", group:61, id:11 },
  {key: "#chief_adv_nilometr", group:61, id:12 },
  {key: "#trade_overseer", group:54, id:0 },
  {key: "#trade_overseer_hint", group:54, id:1 },
  {key: "#building_have_no_access", group:69, id:25 },
  {key: "#bazaar_info_title", group: 97, id:0},
  {key: "#well_info_title", group:109, id:0},
  {key: "#trade_overseer_prices", group:54, id:30},
  {key: "#trade_overseer_prices_hint", group:68, id:108},
  {key: "#trade_overseer_goto_empire", group:54, id:2},
  {key: "#trade_overseer_goto_empire_hint", group:68, id:42},
  {key: "#festival_square_info_title", group:188, id:0},
  {key: "#visit_rating_advisor", group:105, id:3},
  {key: "#gardens_describe", group:79, id:1},
  {key: "#popup_dialog_proceed", group:43, id:5},

  {key: "#must_build_on_cleared_land", group:19, id:0},
  {key: "#out_of_credit", group:19, id:1},
  {key: "#only_one_building_of_this_type", group:19, id:2},
  {key: "#house_evolution_off", group:19, id:3},
  {key: "#house_evolution_on", group:19, id:4},
  {key: "#road_evolution_off", group:19, id:5},
  {key: "#road_evolution_on", group:19, id:6},
  {key: "#show_people_off", group:19, id:7},
  {key: "#show_people_on", group:19, id:8},
  {key: "#needs_road_access", group:19, id:9},
  {key: "#building_not_next_to_water", group:19, id:10},
  {key: "#not_available_in_this_assignment", group:19, id:11},
  {key: "#not_available_yet", group:19, id:12},
  {key: "#unused_alabaster1", group:19, id:13},
  {key: "#unused_alabaster2", group:19, id:14},
  {key: "#city_needs_more_workers", group:19, id:15},
  {key: "#people_eat_more_than_produce", group:19, id:16},
  {key: "#build_bazaars_to_distribute_food", group:19, id:17},
  {key: "#build_farms_on_meadow", group:19, id:18},
  {key: "#build_clay_pits_close_to_water", group:19, id:19},
  {key: "#build_next_to_rocky_areas", group:19, id:20},
  {key: "#build_wood_cutters_next_to_trees", group:19, id:21},
  {key: "#build_next_to_rocky_areas_ex", group:19, id:22},
  {key: "#scout_along_river_for_site", group:19, id:23},
  {key: "#building_needs_copper_ore", group:19, id:24},
  {key: "#needs_barley", group:19, id:25},
  {key: "#building_needs_flax", group:19, id:26},
  {key: "#building_needs_clay", group:19, id:27},
  {key: "#needs_gems", group:19, id:28},
  {key: "#setup_trade_route_to_import", group:19, id:29},
  {key: "#overseer_of_commerce_to_import", group:19, id:30},
  {key: "#build_copper_mine", group:19, id:31},
  {key: "#build_barley_farm", group:19, id:32},
  {key: "#build_flax_farm", group:19, id:33},
  {key: "#build_clay_pit", group:19, id:34},
  {key: "#build_gem_mine", group:19, id:35},
  {key: "#needs_access_to_water_lift", group:19, id:36},
  {key: "#needs_to_be_next_to_water_to_fill", group:19, id:37},
  {key: "#use_irrigation_ditches", group:19, id:38},
  {key: "#must_be_next_to_wall_for_patrol", group:19, id:39},
  {key: "#needs_recruiter_to_conscript", group:19, id:40},
  {key: "#soldiers_need_supplies_of_weapons", group:19, id:41},
  {key: "#build_juggling_school", group:19, id:42},
  {key: "#build_conservatory", group:19, id:43},
  {key: "#build_dance_school", group:19, id:44},
  {key: "#build_senet_house", group:19, id:45},
  {key: "#unused_demo1", group:19, id:46},
  {key: "#build_towers_on_thick_walls", group:19, id:47},
  {key: "#too_close_to_enemy_troops", group:19, id:48},
  {key: "#company_morale_too_low", group:19, id:49},
  {key: "#army_has_full_complement_of_forts", group:19, id:50},
  {key: "#monthly_autosave_on", group:19, id:51},
  {key: "#monthly_autosave_off", group:19, id:52},
  {key: "#cannot_demolish_bridge_with_people", group:19, id:53},
  {key: "#inland_lake_has_no_sea_access", group:19, id:54},
  {key: "#cannot_set_windows_mode", group:19, id:55},
  {key: "#build_reed_gatherers_near_marsh", group:19, id:56},
  {key: "#shipwrights_need_wood_for_war_vessels", group:19, id:57},
  {key: "#palace_required_for_gold_conversion", group:19, id:58},
  {key: "#cannot_build_over_animal_breeding_grounds", group:19, id:59},
  {key: "#plots_too_far_from_road", group:19, id:60},
  {key: "#city_isolated_from_kingdom_road", group:19, id:61},
  {key: "#restore_access_or_sector_will_stagnate", group:19, id:62},
  {key: "#data_limit_reached", group:19, id:63},
  {key: "#only_build_roadblocks_on_roads", group:19, id:64},
  {key: "#place_other_ferry_landing", group:19, id:65},
  {key: "#no_valid_spot_for_ferry_landing", group:19, id:66},
  {key: "#maximum_food_types_reached", group:19, id:67},
  {key: "#cannot_add_meat_without_straw", group:19, id:68},
  {key: "#cannot_produce_meat_in_city", group:19, id:69},
  {key: "#only_one_special_rock_type", group:19, id:70},
  {key: "#must_build_temple_complex_first", group:19, id:71},
  {key: "#temple_complex_limits", group:19, id:72},
  {key: "#oracle_altar_placement", group:19, id:73},
  {key: "#needs_groundwater", group:19, id:74},
  {key: "#entertainment_venue_at_intersection", group:19, id:75},
  {key: "#must_have_completed_temple_first", group:19, id:76},
  {key: "#need_500_papyrus_for_library", group:19, id:77},
  {key: "#building_needs_reeds", group:19, id:78},
  {key: "#build_reed_gatherer", group:19, id:79},
  {key: "#building_needs_straw", group:19, id:80},
  {key: "#build_grain_farm", group:19, id:81},
  {key: "#full_complement_of_warship_wharves", group:19, id:82},
  {key: "#need_100_blocks_of_granite_for_obelisk", group:19, id:83},
  {key: "#need_200_blocks_of_granite_for_large_obelisk", group:19, id:84},
  {key: "#monuments_removed", group:19, id:85},
  {key: "#only_one_obelisk_at_a_time", group:19, id:86},
  {key: "#no_taxes_without_palace", group:19, id:87},
  {key: "#need_220_blocks_of_sandstone_for_sun_temple", group:19, id:88},
  {key: "#only_one_sun_temple_at_a_time", group:19, id:89},
  {key: "#too_few_jobs_for_population", group:19, id:90},
  {key: "#low_food_levels", group:19, id:91},
  {key: "#people_eating_more_than_produced", group:19, id:92},
  {key: "#city_health_appalling_plague_imminent", group:19, id:93},
  {key: "#city_health_terrible_plague_likely", group:19, id:94},
  {key: "#city_health_worsening_serious_risk", group:19, id:95},
  {key: "#city_health_getting_worse_plague_could_strike", group:19, id:96},
  {key: "#plague_likely_health_improving", group:19, id:97},
  {key: "#risk_of_plague_but_improving", group:19, id:98},
  {key: "#health_improving_plague_still_possible", group:19, id:99},
  {key: "#palace_robbed", group:19, id:100},
  {key: "#thief_stole_savings", group:19, id:101},
  {key: "#no_troops_for_defense", group:19, id:102},
  {key: "#loathed_in_city", group:19, id:103},
  {key: "#people_very_angry", group:19, id:104},
  {key: "#people_angry", group:19, id:105},
  {key: "#people_very_upset", group:19, id:106},
  {key: "#people_upset", group:19, id:107},
  {key: "#people_annoyed", group:19, id:108},
  {key: "#people_indifferent", group:19, id:109},
  {key: "#people_pleased", group:19, id:110},
  {key: "#people_very_pleased", group:19, id:111},
  {key: "#people_extremely_pleased", group:19, id:112},
  {key: "#people_love_you", group:19, id:113},
  {key: "#people_idolize_you", group:19, id:114},
  {key: "#unhappiness_lack_of_food", group:19, id:115},
  {key: "#unhappiness_lack_of_jobs", group:19, id:116},
  {key: "#unhappiness_high_taxes", group:19, id:117},
  {key: "#unhappiness_low_wages", group:19, id:118},
  {key: "#unhappiness_too_many_slums", group:19, id:119},
  {key: "#immigration_people_coming", group:19, id:120},
  {key: "#immigration_no_housing", group:19, id:121},
  {key: "#immigration_low_wages_deter", group:19, id:122},
  {key: "#immigration_lack_of_jobs", group:19, id:123},
  {key: "#immigration_lack_of_food", group:19, id:124},
  {key: "#immigration_high_taxes", group:19, id:125},
  {key: "#immigration_slums_deter", group:19, id:126},
  {key: "#immigration_low_sentiment", group:19, id:127},
  {key: "#emigration_no_housing", group:19, id:128},
  {key: "#emigration_low_wages", group:19, id:129},
  {key: "#emigration_high_unemployment", group:19, id:130},
  {key: "#emigration_lack_of_food", group:19, id:131},
  {key: "#emigration_high_taxes", group:19, id:132},
  {key: "#emigration_slums_encourage_leaving", group:19, id:133},
  {key: "#emigration_low_sentiment", group:19, id:134},
  {key: "#building_needs_beer", group:19, id:135},
  {key: "#build_brewery", group:19, id:136},
  {key: "#needs_papyrus", group:19, id:137},
  {key: "#build_papyrus_maker", group:19, id:138},
  {key: "#building_needs_linen", group:19, id:139},
  {key: "#build_weaver", group:19, id:140},
  {key: "#building_needs_wood", group:19, id:141},
  {key: "#build_wood_cutter", group:19, id:142},
  {key: "#building_needs_clay_and_straw", group:19, id:143},
  {key: "#import_clay_trade_route", group:19, id:144},
  {key: "#import_clay_overseer", group:19, id:145},
  {key: "#import_straw_trade_route", group:19, id:146},
  {key: "#import_straw_overseer", group:19, id:147},
  {key: "#monument_needs_stone_and_limestone", group:19, id:148},
  {key: "#build_stone_quarry", group:19, id:149},
  {key: "#import_stone_trade_route", group:19, id:150},
  {key: "#import_stone_overseer", group:19, id:151},
  {key: "#build_limestone_quarry", group:19, id:152},
  {key: "#import_limestone_trade_route", group:19, id:153},
  {key: "#import_limestone_overseer", group:19, id:154},
  {key: "#monument_needs_plain_stone", group:19, id:155},
  {key: "#monument_needs_limestone", group:19, id:156},
  {key: "#monument_needs_bricks_and_limestone", group:19, id:157},
  {key: "#build_brickworks", group:19, id:158},
  {key: "#import_bricks_trade_route", group:19, id:159},
  {key: "#import_bricks_overseer", group:19, id:160},
  {key: "#monument_needs_bricks", group:19, id:161},
  {key: "#monument_needs_sandstone", group:19, id:162},
  {key: "#build_sandstone_quarry", group:19, id:163},
  {key: "#import_beer_overseer", group:19, id:164},
  {key: "#import_beer_trade_route", group:19, id:165},
  {key: "#import_barley_overseer", group:19, id:166},
  {key: "#import_barley_trade_route", group:19, id:167},
  {key: "#import_reeds_overseer", group:19, id:168},
  {key: "#import_reeds_trade_route", group:19, id:169},
  {key: "#import_papyrus_overseer", group:19, id:170},
  {key: "#import_papyrus_trade_route", group:19, id:171},
  {key: "#import_flax_overseer", group:19, id:172},
  {key: "#import_flax_trade_route", group:19, id:173},
  {key: "#import_linen_overseer", group:19, id:174},
  {key: "#import_linen_trade_route", group:19, id:175},
  {key: "#building_removed_mortuaries", group:19, id:176},
  {key: "#building_removed_senet_house", group:19, id:177},
  {key: "#building_removed_scribal_schools", group:19, id:178},
  {key: "#building_removed_libraries", group:19, id:179},
  {key: "#building_removed_weaponsmiths", group:19, id:180},
  {key: "#building_removed_chariot_maker", group:19, id:181},
  {key: "#building_removed_fort_infantry", group:19, id:182},
  {key: "#building_removed_fort_archers", group:19, id:183},
  {key: "#building_removed_fort_charioteers", group:19, id:184},
  {key: "#building_removed_academies", group:19, id:185},
  {key: "#mausoleum_needs_sandstone", group:19, id:186},
  {key: "#build_brewery_or_import_beer", group:19, id:187},
  {key: "#build_papyrus_maker_or_import", group:19, id:188},
  {key: "#build_weaver_or_import_linen", group:19, id:189},
  {key: "#tax_collector_robbed", group:19, id:190},
  {key: "#courthouse_robbed", group:19, id:191},
  {key: "#mansion_destroyed", group:19, id:192},
  {key: "#palace_destroyed", group:19, id:193},
  {key: "#tax_collector_destroyed", group:19, id:194},
  {key: "#courthouse_destroyed", group:19, id:195},
  {key: "#gold_miner_robbed", group:19, id:196},
  {key: "#build_granary", group:19, id:197},
  {key: "#build_granaries", group:19, id:198},
  {key: "#max_docks_reached", group:19, id:199},
  {key: "#shrines_near_road_required", group:19, id:200},
  {key: "#build_jugglers_school", group:19, id:201},
  {key: "#build_conservatory", group:19, id:202},
  {key: "#build_dance_school", group:19, id:203},
  {key: "#company_cannot_reach_destination", group:19, id:204},
  {key: "#game_saved", group:19, id:205},
  {key: "#must_be_on_clear_land", group:19, id:206},
  {key: "#causeway_needs_water", group:19, id:207},
  {key: "#festival_square_on_intersection", group:19, id:208},
  {key: "#no_immigration_with_enemies", group:19, id:209},
  {key: "#cheats_enabled", group:19, id:210},
  {key: "#cheats_disabled", group:19, id:211},
  {key: "#flood_perfect", group:19, id:212},
  {key: "#flood_excellent", group:19, id:213},
  {key: "#flood_good", group:19, id:214},
  {key: "#flood_mediocre", group:19, id:215},
  {key: "#flood_poor", group:19, id:216},
  {key: "#flood_failed", group:19, id:217},
  {key: "#price_increase", group:19, id:218},
  {key: "#price_decrease", group:19, id:219},
  {key: "#wages_lowered", group:19, id:220},
  {key: "#wages_raised", group:19, id:221},
  {key: "#trade_decreases", group:19, id:222},
  {key: "#trade_increases", group:19, id:223},
  {key: "#kingdom_standing_rises", group:19, id:224},
  {key: "#population_milestone", group:19, id:225},
  {key: "#minor_god_blessing", group:19, id:226},
  {key: "#festival_starting", group:19, id:227},
  {key: "#goods_auto_dispatched", group:19, id:228},
  {key: "#building_removed_zoo", group:19, id:229},
  {key: "#building_needs_game_meat", group:19, id:230},
  {key: "#build_hunting_lodge", group:19, id:231},
  {key: "#build_hunting_lodge_or_import", group:19, id:232},
  {key: "#monument_needs_copper", group:19, id:233},
  {key: "#monument_needs_marble", group:19, id:234},
  {key: "#one_library_only", group:19, id:235},
  {key: "#one_pharos_only", group:19, id:236},
  {key: "#one_caesareum_only", group:19, id:237},
  {key: "#disease_strikes", group:19, id:238},
  {key: "#malaria_strikes", group:19, id:239},
  {key: "#monument_needs_granite", group:19, id:240},
  {key: "#must_be_over_rocks", group:19, id:241},
  {key: "#pharos_not_demolishable", group:19, id:242},
  {key: "#tomb_robbers_plundered", group:19, id:243},
  {key: "#mausoleum_plundered", group:19, id:244},
  {key: "#tomb_robbers_stole_provisions", group:19, id:245},
  {key: "#tomb_robber_caught", group:19, id:246},
  {key: "#building_needs_oil_and_pottery", group:19, id:247},
  {key: "#build_potter", group:19, id:248},
  {key: "#import_pottery_trade_route", group:19, id:249},
  {key: "#import_pottery_overseer", group:19, id:250},
  {key: "#import_oil_trade_route", group:19, id:251},
  {key: "#import_oil_overseer", group:19, id:252},
  {key: "#building_needs_henna", group:19, id:253},
  {key: "#build_henna_farm", group:19, id:254},
  {key: "#import_henna_trade_route", group:19, id:255},
  {key: "#import_henna_overseer", group:19, id:256},
  {key: "#building_needs_oil", group:19, id:257},
  {key: "#building_needs_pottery", group:19, id:258},
  {key: "#build_paint_maker_or_import", group:19, id:259},
  {key: "#build_paint_maker", group:19, id:260},
  {key: "#building_needs_clay_and_paint", group:19, id:261},
  {key: "#employees_needed", group:19, id:262},
  {key: "#must_be_over_cliffs", group:19, id:263},
  {key: "#entrance_on_clear_land", group:19, id:264}
  {key: "#warning_shipwright_needed", group:19, id:316}

  {key: "#hunter_ostrich_good_city", lang:"en", text: "I like it here, but there is always room for improvement."},
]
