log_info("akhenaten: load modules started")

include(":math.js")
include(":common.js")
include(":images.js")
include(":city_sounds.js")
include(":mission_sounds.js")
include(":walker_sounds.js")
include(":buildings.js")
include(":overlays.js")
include(":building_sounds.js")
include(":images.js")
include(":images_remap.js")
include(":imagepaks.js")
include(":missions.js")
include(":figures.js")
include(":localization.js")
include(":building_menu.js")
include(":desirability.js")
include(":floodplain.js")
include(":ui.js")
include(":ui_top_menu_widget.js")
