log_info("akhenaten: ui top menu config started")

window top_menu_widget = {
	offset : [10, 6],
	item_height : 20,
	background: IMG_TOP_MENU_BACKGROUND,
	sidebar_offset : 158,
	spacing : 32,
	offset_rotate_basic : 200,

	headers : {
		file 					: { type: "menu_header", text: {group:7, id:0}, tooltip:[68, 51] },
		options				: { type: "menu_header", text: {group:2, id:0}, tooltip:[68, 52] },
		help		   		: { type: "menu_header", text: {group:3, id:0}, tooltip:[68, 53] },
		advisors  		: { type: "menu_header", text: {group:4, id:0} },
		debug		   		: { type: "menu_header", text: "Debug" },
		debug_render  : { type: "menu_header", text: "Render" },
	},

	file : {
		new_game      : { type: "menu_item", text: {group:1, id:1} },
		replay_map    : { type: "menu_item", text: {group:1, id:2} },
		load_game	    : { type: "menu_item", text: {group:1, id:3} },
		save_game	    : { type: "menu_item", text: {group:1, id:4} },
		delete_game	  : { type: "menu_item", text: {group:1, id:6} },
		exit_game	    : { type: "menu_item", text: {group:1, id:5} },
	},

	options : {
		display_options: { type: "menu_item", text: {group:2, id:1} },
		sound_options  : { type: "menu_item", text: {group:2, id:2} },
		speed_options  : { type: "menu_item", text: {group:2, id:3} },
		difficulty_options: { type: "menu_item", text: {group:2, id:6} },
		autosave_options: { type: "menu_item", text: {group:19, id:51} },
		hotkeys_options : { type: "menu_item", text: "Hotkeys options" },
		enhanced_options: { type: "menu_item", text: "Enhanced options" },
	},

	help : {
		help: { type: "menu_item", text: {group:3, id:1} },
		mouse: { type: "menu_item", text: {group:3, id:2} },
		warnings: { type: "menu_item", text: {group:3, id:5} },
		about: { type: "menu_item", text: {group:3, id:7} },
	},

	advisors : {
		advisor_labor 	 :  { type: "menu_item", text:{group: 4, id: ADVISOR_LABOR}, parameter: ADVISOR_LABOR},
    advisor_military :  { type: "menu_item", text:{group: 4, id: ADVISOR_MILITARY}, parameter: ADVISOR_MILITARY},
    advisor_imperial :  { type: "menu_item", text:{group: 4, id: ADVISOR_IMPERIAL}, parameter: ADVISOR_IMPERIAL},
    advisor_ratings  :  { type: "menu_item", text:{group: 4, id: ADVISOR_RATINGS}, parameter: ADVISOR_RATINGS},
    advisor_trade    :  { type: "menu_item", text:{group: 4, id: ADVISOR_TRADE}, parameter: ADVISOR_TRADE},
    advisor_population: { type: "menu_item", text:{group: 4, id: ADVISOR_POPULATION}, parameter: ADVISOR_POPULATION},
    advisor_health   :  { type: "menu_item", text:{group: 4, id: ADVISOR_HEALTH}, parameter: ADVISOR_HEALTH},
    advisor_education:  { type: "menu_item", text:{group: 4, id: ADVISOR_EDUCATION}, parameter: ADVISOR_EDUCATION},
    advisor_entertainment:  { type: "menu_item", text:{group: 4, id: ADVISOR_ENTERTAINMENT}, parameter: ADVISOR_ENTERTAINMENT},
    advisor_religion :  { type: "menu_item", text:{group: 4, id: ADVISOR_RELIGION}, parameter: ADVISOR_RELIGION},
    advisor_financial:  { type: "menu_item", text:{group: 4, id: ADVISOR_FINANCIAL}, parameter: ADVISOR_FINANCIAL},
    advisor_chief    :  { type: "menu_item", text:{group: 4, id: ADVISOR_CHIEF}, parameter: ADVISOR_CHIEF},
	},

	debug : {
		pages 				: { type : "menu_item", text: "", parameter: 0},
		game_time 		: { type : "menu_item", text: "", parameter: 1},
		build_planner : { type : "menu_item", text: "", parameter: 2},
		religion 			: { type : "menu_item", text: "", parameter: 3},
		tutorial 			: { type : "menu_item", text: "", parameter: 4},
		floods 				: { type : "menu_item", text: "", parameter: 5},
		camera 				: { type : "menu_item", text: "", parameter: 6},
		tile_cache 		: { type : "menu_item", text: "", parameter: 7},
		migration 		: { type : "menu_item", text: "", parameter: 8},
 		sentiment 		: { type : "menu_item", text: "", parameter: 9},
 		sound_channels: { type : "menu_item", text: "", parameter: 10},
 		properties		: { type : "menu_item", text: "", parameter: 11},
 		show_console  : { type : "menu_item", text: "", parameter: 12},
 		make_screenshot : { type : "menu_item", text: "", parameter: 13},
 		make_full_screenshot : { type : "menu_item", text: "", parameter: 14},
 		write_video   : { type : "menu_item", text: "", parameter: 15},
	},

	debug_render : {
    building 			: { type : "menu_item", text:"", parameter:1},
    tilesize 			: { type : "menu_item", text:"", parameter:2},
    roads 				: { type : "menu_item", text:"", parameter:3},
    routing_dist 	: { type : "menu_item", text:"", parameter:4},
    routing_grid 	: { type : "menu_item", text:"", parameter:5},
    moisture 			: { type : "menu_item", text:"", parameter:6},
    grass_level 	: { type : "menu_item", text:"", parameter:7},
    grass_soil_depletion: { type : "menu_item", text:"", parameter:8},
    grass_flood_order		: { type : "menu_item", text:"", parameter:9},
    grass_flood_flags		: { type : "menu_item", text:"", parameter:10},
    labor 			  : { type : "menu_item", text:"", parameter:11},
    sprite_frames : { type : "menu_item", text:"", parameter:12},
    terrain_bits 	: { type : "menu_item", text:"", parameter:13},
    image 			  : { type : "menu_item", text:"", parameter:14},
    image_alt 		: { type : "menu_item", text:"", parameter:15},
    marshland 		: { type : "menu_item", text:"", parameter:16},
    terrain_type 	: { type : "menu_item", text:"", parameter:17},
    tile_pos 			: { type : "menu_item", text:"", parameter:20},
    floodplain_shore: { type : "menu_item", text:"", parameter:21},
    tile_toph 		: { type : "menu_item", text:"", parameter:22},
    monuments 		: { type : "menu_item", text:"", parameter:23},
    figures 			: { type : "menu_item", text:"", parameter:24},
    height 			  : { type : "menu_item", text:"", parameter:25},
    marshland_depl: { type : "menu_item", text:"", parameter:26},
    damage_fire 	: { type : "menu_item", text:"", parameter:27},
    desirability 	: { type : "menu_item", text:"", parameter:28},
    shoreline   	: { type : "menu_item", text:"", parameter:29},
	},

	ui : {
		background 		: dummy({size:[sw(0), 30]}),
		date          : link({pos:[0, 2], margin:{right: -150}, size:[117, 20], hbody:false, border:false, font_hover:FONT_NORMAL_YELLOW, tooltip:[68, 63] }),
		population    : link({pos:[0, 2], margin:{right: -320}, size:[117, 20], hbody:false, border:false, font_hover:FONT_NORMAL_YELLOW, tooltip:[68, 62] }),
		funds         : link({pos:[0, 2], margin:{right: -450}, size:[117, 20], hbody:false, border:false, font_hover:FONT_NORMAL_YELLOW, tooltip:[68, 62] }),
	}
}
