#pragma once

#include <stdint.h>
#include "core/bstring.h"

enum {
    WARNING_ORIENTATION = 1,
    WARNING_CLEAR_LAND_NEEDED = 2,
    WARNING_OUT_OF_MONEY = 3,
    WARNING_ONE_BUILDING_OF_TYPE = 4,
    WARNING_WATER_NEARBY_NEEDED = 10,
    WARNING_ROAD_ACCESS_NEEDED = 11,
    WARNING_NOT_AVAILABLE = 13,
    WARNING_NOT_AVAILABLE_YET = 14,
    WARNING_MARBLE_NEEDED_LARGE_TEMPLE = 15,
    WARNING_MARBLE_NEEDED_ORACLE = 16,
    WARNING_WORKERS_NEEDED = 17,
    WARNING_MORE_FOOD_NEEDED = 18,
    WARNING_BUILD_MARKET = 19,
    WARNING_MEADOW_NEEDED = 20,
    WARNING_WATER_NEEDED = 21,
    WARNING_ROCK_NEEDED = 22,
    WARNING_TREE_NEEDED = 23,
    WARNING_COPPER_NEEDED = 24,
    WARNING_BARLEY_NEEDED = 25,
    WARNING_FLAX_NEEDED = 26,
    WARNING_CLAY_NEEDED = 27,
    WARNING_GEMS_NEEDED = 28,
    WARNING_OPEN_TRADE_TO_IMPORT = 29,
    WARNING_TRADE_IMPORT_RESOURCE = 30,
    WARNING_BUILD_COPPER_MINE = 31,
    WARNING_BUILD_BARLEY_FARM = 32,
    WARNING_BUILD_FLAX_FARM = 33,
    WARNING_BUILD_CLAY_PIT = 34,
    WARNING_BUILD_GEM_MINE = 35,
    WARNING_NEED_ACCESS_TO_WATER_LIFT = 36,
    WARNING_BUILD_NEAR_WATER = 37,
    WARNING_WATER_ACCESS_NEEDED = 38,
    WARNING_SENTRIES_NEED_WALL = 39,
    WARNING_CONNECT_TO_WATERLIFT = 40,
    WARNING_WEAPONS_NEEDED = 41,
    WARNING_BUILD_JUGGLER_SCHOOL = 42,
    WARNING_BUILD_CONSERVATORY = 43,
    WARNING_BUILD_DANCERS_SCHOOL = 44,
    WARNING_BUILD_SENET_MAKER = 45,
    WARNING_UNUSUAL_DEMO_1 = 46,
    WARNING_ONLY_BUILD_TOWERS_ON_THICK_WALLS = 47,
    WARNING_ENEMY_NEARBY = 48,
    WARNING_COMPANY_MORALE_TOO_LOW = 49,
    WARNING_MAX_COMPANY_REACHED = 50,
    WARNING_MONTLY_AUTOSAVE_ON = 51,
    WARNING_MONTLY_AUTOSAVE_OFF = 52,
    WARNING_PEOPLE_ON_BRIDGE = 55,
    WARNING_DOCK_OPEN_WATER_NEEDED = 56,
    WARNING_EDITOR_NEED_MAP_EDGE = 58,
    WARNING_EDITOR_NEED_OPEN_WATER = 59,
    WARNING_EDITOR_CANNOT_PLACE = 60,
    WARNING_EDITOR_NO_EARTHQUAKE_SCHEDULED = 61,
    WARNING_HERD_BREEDING_GROUNDS = 61,
    WARNING_HOUSE_TOO_FAR_FROM_ROAD = 62,
    WARNING_CITY_BOXED_IN = 63,
    WARNING_CITY_BOXED_IN_PEOPLE_WILL_PERISH = 64,
    WARNING_DATA_LIMIT_REACHED = 65,
    //
    WARNING_ROADBLOCKS_ROAD_NEEDED = 66,
    WARNING_FERRY_PLACE_OTHER_ONE = 67,
    WARNING_FERRY_INVALID_SPOT = 68,

    WARNING_TEMPLE_UPGRADE_ONLY_ONE = 72,
    WARNING_TEMPLE_COMPLEX_MISSING = 73,
    WARNING_WATER_PIPE_ACCESS_NEEDED = 74,
    WARNING_TEMPLE_UPGRADE_PLACEMENT_NEED_TEMPLE = 75,

    WARNING_GROUNDWATER_NEEDED = 76,
    WARNING_BOOTH_ROAD_INTERSECTION_NEEDED = 77,
    WARNING_NEED_COMPLETED_TEMPLE = 78,
    WARNING_NEED_REEDS = 78,
    WARNING_BUILD_REEDS_GATHERER = 79,
    WARNING_NEED_STRAW = 80,
    WARNING_NEED_GRAIN_FARM = 81,
    WARNING_500_PAPYRUS_NEEDED = 79,
    WARNING_NEED_STRAW_2 = 83,
    WARNING_WARSHIP_FULL = 84,
    WARNING_100_GRANITE_OBELISK_NEEDED = 85,
    WARNING_200_GRANITE_OBELISK_NEEDED = 86,
    WARNING_SOME_MONUMENTS_NO_LONGER_AVAILABLE = 87,
    WARNING_OBELISK_ONLY_ONE = 88,
    WARNING_TAXES_PALACE_NEEDED = 89,
    WARNING_220_SANDSTONE_SUNTEMPLE_NEEDED = 90,
    WARNING_SUNTEMPLE_ONLY_ONE = 91,
    WARNING_TOO_FEW_JOBS = 92,
    WARNING_FOOD_LEVELS_LOW = 93,
    WARNING_EATING_MORE_THAN_PRODUCED = 94,

    WARNING_PALACE_ROBBED = 102,
    WARNING_MANSION_ROBBED = 103,
    WARNING_NO_TROOPS = 104,

    WARNING_PAPYRUS_NEEDED = 139,
    WARNING_BUILD_PAPYRUS_MAKER = 140,

    WARNING_INSTRUCT_OVERSEER_TO_IMPORT_REED = 168,
    WARNING_OPEN_TRADE_TO_IMPORT_REED = 169,

    WARNING_INSTRUCT_OVERSEER_TO_IMPORT_PAPYRUS = 172,
    WARNING_OPEN_TRADE_TO_IMPORT_PAPYRUS = 173,

    WARNING_BUILD_RECRUITER = 182,

    WARNING_FESTIVAL_ROAD_INTERSECTION_NEEDED = 215,
    WARNING_SHIPWRIGHT_NEEDED = 316,
};

void city_warning_show(int type);
void city_warning_show_custom(const char *text);

int city_has_warnings();

pcstr city_warning_get(int id);

void city_warning_clear_all();
void city_warning_clear_outdated();

void city_warning_show_console(pcstr warning_text);

template<typename ... Args>
void city_warning_show_console_var(pcstr fmt, Args... args) {
    bstring1024 buffer;
    buffer.printf(fmt, args...);
    city_warning_show_console(buffer);
}
